version: '3.8'

networks:
  web-services:
    driver: bridge

services:
  node-app:
    build: ./node-app
    volumes:
      - ./node-app:/usr/src/app
      - ./cert-data:/etc/letsencrypt
      - /usr/src/app/node_modules
    depends_on:
      - certbot
    networks:
      - web-services

  certbot:
    image: certbot/dns-cloudflare
    ports:
      - 80:80
    volumes:
      - ./cert-data:/etc/letsencrypt
      - ./certbot:/app
      - ./certbot/entrypoint.sh:/app/entrypoint.sh
    environment:
      - CERTBOT_EMAIL=/run/secrets/email
      - CERTBOT_DOMAIN=/run/secrets/domain-name
    secrets:
      - domain-name
      - email
    entrypoint: ["sh", "/app/entrypoint.sh"]   

  nginx:
    image: nginx:latest 
    hostname: nginx
    ports:
      - "443:443" # Add port 443 for HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert-data:/etc/letsencrypt
      - ./webroot-data:/var/www/certbot
    depends_on:
      - node-app
      - certbot
    networks:
      - web-services

  


  arch-mirror:
    build: ./sync/arch
    volumes:
      - ./sync/arch/syncrepo-arch.sh:/app/syncrepo-arch.sh
      - ./sync/arch/arch-mirror-cron:/etc/cron.d/arch-mirror-cron
      - ./node-app/mirror/arch:/app/arch
      - ./sync/arch/log:/app/log

  ftpsync-debian:
    build: ./sync/debian-ftpsync
    volumes:
      - ./sync/debian-ftpsync/log:/home/ftpsync/log
      - ./sync/debian-ftpsync/bin:/home/ftpsync/bin
      - ./sync/debian-ftpsync/etc:/home/ftpsync/etc
      - ./node-app/mirror/debian:/home/ftpsync/mirrors/debian/
      
  rsync:
    build: ./sync/rsync
    ports:
      - 873:873
    volumes:
      - ./sync/rsync/rsyncd.conf:/etc/rsyncd.conf
      - ./node-app/mirror:/app/mirror
      - ./sync/rsync/log:/var/log

secrets:
  domain-name:
    file: ./certbot/domain.txt # put domain name in this file
  email:
    file: ./certbot/email.txt # put email in this file
  
  

  

  