version: '3.8'

networks:
  web-services:
    driver: bridge

services:
  node-app:
    build: ./node-app
    volumes:
      - ./node-app:/usr/src/app
      - ./cert-data:/etc/letsencrypt
      - /usr/src/app/node_modules
    depends_on:
      - nginx
    networks:
      - web-services

  nginx:
    image: nginx:latest 
    hostname: nginx
    ports:
      - "8443:443" # Add port 8443 for dev
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert-data:/etc/letsencrypt
      - ./webroot-data:/var/www/certbot
    networks:
      - web-services



  