version: '3.8'

networks:
  web-services:
    driver: bridge

services:
  node-app:
    build: ./node-app
    volumes:
      - ./node-app:/usr/src/app
      - ./cert-data:/etc/letsencrypt
      - /usr/src/app/node_modules
    depends_on:
      - certbot
    networks:
      - web-services

  nginx:
    image: nginx:latest 
    hostname: nginx
    ports:
      - "443:443" # Add port 443 for HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert-data:/etc/letsencrypt
      - ./webroot-data:/var/www/certbot
    depends_on:
      - node-app
      - certbot
    networks:
      - web-services

  certbot:
    image: certbot/certbot
    ports:
      - 80:80
    volumes:
      - ./cert-data:/etc/letsencrypt
      - ./webroot-data:/var/www/html
    environment:
      - CERTBOT_EMAIL=mirror@muxoid.com
      - CERTBOT_DOMAIN=acadielinux.ca
    command: certonly --standalone -m mirror@muxoid.com --keep-until-expiring --agree-tos --no-eff-email -d mirror.acadielinux.ca # Change domain and email to your own if you want to clone.
    


  apt-mirror-debian:
    build: ./sync/debian
    volumes:
      - ./sync/debian/mirror.list:/etc/apt/mirror.list
      - ./sync/debian/apt-mirror-cron:/etc/cron.d/apt-mirror-cron
      - ./node-app/mirror/debian:/app/mirror.csclub.uwaterloo.ca/debian

     

  apt-mirror-ubuntu:
    build: ./sync/ubuntu
    volumes:
      - ./sync/ubuntu/mirror.list:/etc/apt/mirror.list
      - ./sync/ubuntu/apt-mirror-cron:/etc/cron.d/apt-mirror-cron
      - ./node-app/mirror/ubuntu:/app/mirror.csclub.uwaterloo.ca/ubuntu

  

  